package com.example.financemanager.entities;

import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Entity representing a user in the Finance Manager system.
 *
 * <p>Each user has a unique username and email address, and can have multiple
 * associated transactions. The user's password is stored in encrypted form using
 * BCrypt hashing.</p>
 *
 * <p>Users can set their preferred language (English or Turkish) for the UI,
 * which is stored in the database and persists across sessions.</p>
 *
 * <h3>Relationships:</h3>
 * <ul>
 *   <li>One-to-Many with Transaction: A user can have multiple transactions</li>
 * </ul>
 *
 * @author Finance Manager Team
 * @version 1.0
 * @since 2025-01-28
 * @see Transaction
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier for the user.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * List of all transactions belonging to this user.
     * Mapped by the 'user' field in the Transaction entity.
     * Cascade operations are not enabled to allow manual control over transaction lifecycle.
     */
    @OneToMany(mappedBy = "user")
    private List<Transaction> transactions = new ArrayList<>();

    /**
     * The user's unique username.
     * Must be between 3 and 50 characters.
     * Used for login authentication.
     */
    private String username;

    /**
     * The user's email address.
     * Must be unique across all users.
     * Used for account identification and potential future features (password reset, notifications).
     */
    private String email;

    /**
     * The user's password, stored in BCrypt encrypted format.
     * Never stored or transmitted in plain text.
     * BCrypt strength: 10 rounds (default).
     */
    private String password;

    /**
     * The user's preferred language for the user interface.
     * Supports "en" (English) and "tr" (Turkish).
     * Defaults to "en" if not specified.
     * Persists across sessions.
     */
    @Column(name = "preferred_language")
    private String preferredLanguage = "en";

    /**
     * Default constructor required by JPA.
     * Initializes preferred language to English.
     */
    public User() {
        this.preferredLanguage = "en";
    }

    /**
     * Constructs a new User with the specified credentials.
     * Preferred language is set to English by default.
     *
     * @param username the unique username (3-50 characters)
     * @param email the unique email address
     * @param password the password in encrypted (BCrypt) format
     */
    public User(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.preferredLanguage = "en";
    }

    // Getters and setters

    /**
     * Gets the user's unique identifier.
     *
     * @return the user ID
     */
    public long getId() {
        return id;
    }

    /**
     * Gets all transactions associated with this user.
     *
     * @return list of transactions (may be empty but never null)
     */
    public List<Transaction> getTransactions() {
        return transactions;
    }

    /**
     * Gets the user's username.
     *
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Gets the user's email address.
     *
     * @return the email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Gets the user's encrypted password.
     *
     * @return the BCrypt-encrypted password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the user's unique identifier.
     * Typically only used by JPA during entity persistence.
     *
     * @param id the user ID to set
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Sets the user's username.
     *
     * @param username the username to set (must be 3-50 characters)
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Sets the user's email address.
     *
     * @param email the email address to set (must be unique and valid format)
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Sets the user's password.
     * Note: Password should be encrypted with BCrypt before calling this method.
     *
     * @param password the encrypted password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Gets the user's preferred UI language.
     *
     * @return the language code ("en" or "tr")
     */
    public String getPreferredLanguage() {
        return preferredLanguage;
    }

    /**
     * Sets the user's preferred UI language.
     * Changes take effect immediately and persist across sessions.
     *
     * @param preferredLanguage the language code to set ("en" for English, "tr" for Turkish)
     */
    public void setPreferredLanguage(String preferredLanguage) {
        this.preferredLanguage = preferredLanguage;
    }

}
